=== YoussefAKQ/Aprendizajes-Programacion-DAM-y-Autodidacta/DAM-Primer-Curso/Lenguaje-de-Marcas/HojaEjercicios6/Ejercicio_1/facturasdtd.dtd
<!ELEMENT facturas (factura*)>
<!ELEMENT factura (num-fac, cod_cliente, articulo+)>
<!ELEMENT num-fac (#PCDATA)>
<!ELEMENT cod_cliente (#PCDATA)>
<!ELEMENT articulo (cod_articulo, nom_articulo, cantidad, precio)>
<!ELEMENT cod_articulo (#PCDATA)>
<!ELEMENT nom_articulo (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ATTLIST factura facturaID CDATA #REQUIRED>

=== YoussefAKQ/Aprendizajes-Programacion-DAM-y-Autodidacta/DAM-Primer-Curso/Lenguaje-de-Marcas/HojaEjercicios6/Ejercicio_2/facturas.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="estilo.css"?>
<!DOCTYPE facturas SYSTEM "facturasdtd.dtd">
<facturas>
    <factura facturaID="1111">
      <num-fac>Factura: 1</num-fac>
      <cod_cliente>Cliente: 0011</cod_cliente>
      <articulo>
        ARTICULO: 
        <cod_articulo>Codigo: 0001</cod_articulo>
        <nom_articulo>Nombre:PAN</nom_articulo>
        <cantidad>Cantidad: 2</cantidad> 
        <precio>Precio: 3</precio> 
      </articulo>
    </factura>
    <factura facturaID="2222">
      <num-fac> Factura: 2</num-fac>
      <cod_cliente> Cliente: 0055</cod_cliente>
      <articulo>
        ARTICULO: 
        <cod_articulo>Codigo: 002</cod_articulo>
        <nom_articulo>Nombre: AGUA</nom_articulo>
        <cantidad>Cantidad: 4</cantidad>
        <precio>Precio: 5</precio> 
      </articulo>
    </factura>
    <factura facturaID="3333">
      <num-fac> Factura: 3</num-fac>
      <cod_cliente> Cliente: 0023</cod_cliente>
      <articulo>
        <cod_articulo>Codigo: 003</cod_articulo>
        <nom_articulo>Nombre: Pescado</nom_articulo>
        <cantidad>Cantidad: 1</cantidad>
        <precio>Precio: 10</precio> 
      </articulo>
    </factura>
</facturas>

=== YoussefAKQ/Aprendizajes-Programacion-DAM-y-Autodidacta/DAM-Primer-Curso/Lenguaje-de-Marcas/HojaEjercicios6/Ejercicio_1/facturas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE facturas SYSTEM "facturasdtd.dtd">
<facturas>
    <factura facturaID="1111">
      <num-fac> 1111</num-fac>
      <cod_cliente> 32D</cod_cliente>
      <articulo>
        <cod_articulo>123</cod_articulo>
        <nom_articulo>123</nom_articulo>
        <cantidad>123</cantidad>
        <precio>123</precio> 
      </articulo>
      <articulo>
        <cod_articulo>321</cod_articulo>
        <nom_articulo>321</nom_articulo>
        <cantidad>321</cantidad>
        <precio>321</precio> 
      </articulo>
    </factura>
</facturas>
