=== YoussefAKQ/Aprendizajes-Programacion-DAM-y-Autodidacta/DAM-Primer-Curso/Lenguaje-de-Marcas/Etc/Practicar xml/XML/recetas.dtd
<!ELEMENT recetas (receta*)>
<!ELEMENT receta (ingrediente*,propietario)>
<!ELEMENT propietario (#PCDATA)>
<!ELEMENT ingrediente (#PCDATA)>
<!ATTLIST receta precio CDATA #REQUIRED>
<!ATTLIST receta nombre CDATA #REQUIRED>

=== YoussefAKQ/Aprendizajes-Programacion-DAM-y-Autodidacta/DAM-Primer-Curso/Lenguaje-de-Marcas/Etc/Practicar xml/XML/recetas.xml
<?xml version="1.0"?>
<!DOCTYPE recetas SYSTEM "recetas.dtd">
<recetas>
<receta nombre="Paella" precio="10">
<ingrediente> Arroz </ingrediente>
<ingrediente> Sepia </ingrediente>
<ingrediente> Gambas </ingrediente>
<propietario>Pilar</propietario>
</receta>
<receta nombre="Tortilla" precio="10">
<ingrediente> Huevos </ingrediente>
<ingrediente> Patata </ingrediente>
</receta>
</recetas>
